---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/12/20 11:03
---
local key1 = KEYS[1];
local arg1 = ARGV[1];
--local v1 = redis.call("set",key1,arg1);
local v2 = redis.call("get",key1);
return v2